Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.network "forwarded_port", guest: 80, host:8088
  config.vm.network "public_network", type: "dhcp"

  config.vm.provision "shell", inline: "
    sudo apt update -y && \
    sudo apt install -y apache2 && \
    sudo apt install -y mysql-server && \
    sudo apt install -y php"

  config.vm.provider "virtualbox" do |v|
  v.memory = 3024
  v.cpus = 4
  v.name = "Maquina"

  end
end
