Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.network "forwarded_port", guest: 80, host:8080
  config.vm.network "public_network", type: "dhcp"

  config.vm.provision "shell", inline: "sudo apt update &&\
  sudo apt install -y nginx"
  config.vm.provider "virtualbox" do |v|
  v.memory = 4024
  v.cpus = 4
  v.name = "Nginx"

end
end
