$script_lamp = <<-SCRIPT
apt update -y && \
apt install -y apache2 && \
apt install -y mysql-server && \
apt install -y php
SCRIPT


Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.network "forwarded_port", guest: 80, host:8089
  config.vm.network "public_network", type: "dhcp"

  config.vm.provision "shell", inline: $script_lamp
   config.vm.synced_folder "./configs", "/configs"
  config.vm.provider "virtualbox" do |v|
  v.memory = 3024
  v.cpus = 4
  v.name = "mapea"

end
end
